max_samples: 100

num_of_itr: 1

train_paths:
  - '/Users/juliankleutgens/training_data'


test_paths:
  - '/Users/juliankleutgens/PycharmProjects/task2seq_T5/data_test/ct_schema'
  - '/Users/juliankleutgens/PycharmProjects/task2seq_T5/data_test/gl_schema'
  - '/Users/juliankleutgens/PycharmProjects/task2seq_T5/data_test/or_schema'

load_new_mappings: true

sparse_type: 'repeated2words'

device: 'cpu'

output_dir: './outputs/'

extra_token:
  - 'sym_aft_func'
  - 'BoF'
  - 'EoF'
  - 'var_to_num'

model_params:
  MODEL: "t5-small"
  TRAIN_BATCH_SIZE: 2
  VALID_BATCH_SIZE: 1
  TRAIN_EPOCHS: 1
  VAL_EPOCHS: 1
  LEARNING_RATE: 1.0e-4
  MAX_SOURCE_TEXT_LENGTH: 2048
  MAX_TARGET_TEXT_LENGTH: 512
  SEED: 42

wandb:
  wandb_user: #"your_wandb_user"
  wandb_project: #"your_wandb_project"
  wandb_run_name: #"your_wandb_run_name"  # Optional
  wandb_notes: #"your_wandb_notes"        # Optional