wandb_version: 1

max_samples:
  desc: null
  value: 2
train_paths:
  desc: null
  value:
  - /data/ct_schema
test_paths:
  desc: null
  value:
  - /data_test/ct_schema
  - /data_test/gl_schema
load_new_mappings:
  desc: null
  value: false
extra_token:
  desc: null
  value:
  - sym_aft_func
  - BoF
  - EoF
  - var_to_num
model_params:
  desc: null
  value:
    MODEL: t5-small
    TRAIN_BATCH_SIZE: 2
    VALID_BATCH_SIZE: 8
    TRAIN_EPOCHS: 1
    VAL_EPOCHS: 1
    LEARNING_RATE: 1e-4
    MAX_SOURCE_TEXT_LENGTH: 2048
    MAX_TARGET_TEXT_LENGTH: 256
    SEED: 42
wandb:
  desc: null
  value:
    wandb_user: null
    wandb_project: null
    wandb_run_name: null
    wandb_notes: null
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716035030.0
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.6
      6: 4.39.3
      8:
      - 5
      13: darwin-arm64
